services:
  # ==========================================
  # --- INFRAESTRUCTURA DE BASES DE DATOS ---
  # ==========================================
  
  db-usuarios:
    image: postgres:16-alpine
    container_name: db-usuarios
    environment:
      POSTGRES_DB: db_clinica_usuarios
      POSTGRES_USER: user_clinica
      POSTGRES_PASSWORD: password_clinica
    ports:
      - "5432:5432" 
    volumes:
      - ./ms-usuarios/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - clinica-network

  # ==========================================
  # --- MICROSERVICIOS BACKEND ---
  # ==========================================

  ms-usuarios:
    build: 
      context: ./ms-usuarios
    container_name: ms-usuarios
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-usuarios:5432/db_clinica_usuarios
      SPRING_DATASOURCE_USERNAME: user_clinica
      SPRING_DATASOURCE_PASSWORD: password_clinica
      # Mismo origen que el front (Vite) para validación Origin/Referer en login y refresh
      APP_ALLOWED_ORIGINS: ${APP_ALLOWED_ORIGINS:-http://localhost:5173}
    depends_on:
      - db-usuarios
    networks:
      - clinica-network

  # ==========================================
  # --- API GATEWAY ---
  # ==========================================

  api-gateway:
    build: 
      context: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      APP_GATEWAY_CORS_ALLOWED_ORIGIN: ${APP_GATEWAY_CORS_ALLOWED_ORIGIN:-http://localhost:5173}
    depends_on:
      - ms-usuarios
    networks:
      - clinica-network

  # ==========================================
  # --- FRONTEND (REACT + VITE) ---
  # ==========================================
  
  frontend-clinica:
    build: 
      context: ./frontend-clinica
      dockerfile: Dockerfile
    container_name: frontend-clinica
    ports:
      - "5173:5173"
    volumes:
      # Sincroniza el código local con el contenedor para ver cambios al instante
      - ./frontend-clinica:/app
      # Evita que se sobreescriba la carpeta node_modules del contenedor
      - /app/node_modules
    environment:
      # Fuerza a Vite a buscar cambios en los archivos (esencial para Windows)
      - CHOKIDAR_USEPOLLING=true
    networks:
      - clinica-network

# ==========================================
# --- CONFIGURACIÓN DE RED ---
# ==========================================
networks:
  clinica-network:
    driver: bridge