server:
  port: 8080 # Puerto de entrada principal para React y Postman

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      # Configuración global de CORS para que Vite (React) pueda comunicarse sin bloqueos
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: 
              - "http://localhost:5173" # Puerto por defecto de Vite
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
      
      # Definición de las rutas hacia tus microservicios
      routes:
        - id: ms-usuarios
          # Usamos el nombre exacto del contenedor en la red de Docker Compose
          uri: http://ms-usuarios:8081
          predicates:
            # Captura todas las peticiones que empiecen con /usuarios
            - Path=/usuarios/**
          filters:
            # Elimina la primera parte del path ("/usuarios") antes de enviar al microservicio
            # Ejemplo: /usuarios/api/pacientes/registro -> /api/pacientes/registro
            - StripPrefix=1