version: '3.8'
services:
  postgres-db:
    image: postgres:15-alpine
    container_name: clinica-postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ojedaTaboada1979
      # Esta DB por defecto se crea sola, las otras se crean con el init.sql
      POSTGRES_DB: clinica_default 
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: