server:
  port: 8081  # Puerto específico para el microservicio de usuarios

spring:
  application:
    name: ms-usuarios
  
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://db-usuarios:5432/db_clinica_usuarios}
    username: ${SPRING_DATASOURCE_USERNAME:user_clinica}
    password: ${SPRING_DATASOURCE_PASSWORD:password_clinica}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # --- CONFIGURACIÓN DE CORREO (NUEVA) ---
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:meganachoj@gmail.com}
    password: ${MAIL_PASSWORD:ntsc wmsy zlva rzzc}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.timeout: 5000
      mail.smtp.connectiontimeout: 5000
      mail.smtp.writetimeout: 5000

  security:
    user:
      name: ${SPRING_SECURITY_USER_NAME:admin_generico}
      password: ${SPRING_SECURITY_USER_PASSWORD:password_generico}

# Configuración de Seguridad JWT
jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
  expiration: ${JWT_EXPIRATION:86400000}

# --- CONFIGURACIÓN DE SISTEMA ---
system:
  registration:
    # Header 'X-System-Key'
    secret: ${ADMIN_REGISTRATION_SECRET:utn_frc_2026_secret_key}
    # Taboada45934779#
    # ignaciotaboada5@hotmail.com


# --- URL DEL GATEWAY PARA LINKS ---
app:
  url: ${APP_URL:http://localhost:8080}