services:
  db-usuarios:
    image: postgres:16-alpine
    container_name: db-usuarios
    environment:
      POSTGRES_DB: db_clinica_usuarios
      POSTGRES_USER: user_clinica
      POSTGRES_PASSWORD: password_clinica
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  ms-usuarios:
    build: .
    container_name: ms-usuarios
    ports:
      # ERROR CORREGIDO: El MS debe exponer el 8081 para no chocar con el Gateway
      - "8081:8081" 
    environment:
      # Mantenemos el nombre del servicio para la red interna de Docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-usuarios:5432/db_clinica_usuarios
      SPRING_DATASOURCE_USERNAME: user_clinica
      SPRING_DATASOURCE_PASSWORD: password_clinica
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      # Agregamos esta propiedad para asegurar que el puerto interno sea 8081
      SERVER_PORT: 8081
    depends_on:
      - db-usuarios